#!/bin/sh
# Source-level smoke test driver for examples/javaN/ fixtures.
#
# For each .java file in examples/javaN/:
#   * Positive translate at -source N -> expect success.
#   * If the file is a known feature fixture (Foreach, Varargs, etc.),
#     also translate at -source 1.4 (or a configured "previous" level)
#     and expect a version-gate error.
#
# Prereqs (verified at startup):
#   * classpath-0.93/ unpacked at repo root
#   * jcgo.jar built (mkjcgo/build-java.sh)

set -e

cd $(dirname "$0")/..

if [ ! -d classpath-0.93 ]; then
    echo "skip: classpath-0.93/ not present (see mkjcgo/build-java.sh prereqs)"
    exit 0
fi
if [ ! -f jcgo.jar ]; then
    echo "skip: jcgo.jar not built — run mkjcgo/build-java.sh first"
    exit 0
fi

# Source paths threaded into every translate, mirrors what jcgo.jar would
# pick up via @stdpaths.in but inlined to avoid the rflg_out dependency
# (rflg_out is generated by build-java.sh; we don't need it for parse +
# pass1 + pass2 of these tiny fixtures).
SRCS="-src goclsp/clsp_asc -src goclsp/clsp_fix -src goclsp/clsp_ldr"
SRCS="$SRCS -src goclsp/clsp_res -src goclsp/vm -src classpath-0.93"

OUTROOT=.build_tmp/source-levels
rm -rf "$OUTROOT"
mkdir -p "$OUTROOT"

# Versions with real fixtures (pure-mirror dirs 6/12/13/18/19/20 skipped):
versions="5 7 8 9 10 11 14 15 16 17 21"

# Per-version "previous" level used for negative tests (file is expected
# to fail with a version-gate error). Default is 1.4; once newer slices
# land, refine per file.
prev_for_5=1.4
prev_for_7=6
prev_for_8=7
prev_for_10=9
prev_for_16=15

# Whitelist of (version, classname) pairs that should ALSO be tested
# negatively. These are fixtures known to depend on a feature gated at
# the matching -source level. Files outside this list run only the
# positive test (since they may be pre-modern code that translates at
# any level).
neg_5="Foreach Varargs StaticImport Annotations AnnotationType"
neg_7="MultiCatch StringSwitch"
neg_8="DefaultIface"
neg_10="VarLocal VarFor VarForeach"
neg_16="PatternInstanceof"

pass=0
fail=0
neg_pass=0
neg_fail=0

skip=0

run_positive() {
    ver=$1; cls=$2; src="examples/java$ver/$cls.java"; outdir="$OUTROOT/java$ver/$cls"
    if [ -f "$src" ] && head -3 "$src" | grep -q "JCGO-SKIP"; then
        skip=$((skip + 1))
        echo "  skip: java$ver $cls (JCGO-SKIP marker)"
        return
    fi
    mkdir -p "$outdir"
    if java -Xss1M -jar jcgo.jar -source "$ver" -d "$outdir" \
            -src "examples/java$ver" $SRCS "$cls" >"$outdir/stdout" 2>&1; then
        pass=$((pass + 1))
        echo "  pass: java$ver $cls (-source $ver)"
    else
        fail=$((fail + 1))
        echo "  FAIL: java$ver $cls (-source $ver)"
        sed -n 's/^/    /p' "$outdir/stdout"
    fi
}

run_negative() {
    ver=$1; cls=$2; prev=$3; outdir="$OUTROOT/java$ver/${cls}_neg"
    mkdir -p "$outdir"
    if java -Xss1M -jar jcgo.jar -source "$prev" -d "$outdir" \
            -src "examples/java$ver" $SRCS "$cls" >"$outdir/stdout" 2>&1; then
        neg_fail=$((neg_fail + 1))
        echo "  NEG FAIL: java$ver $cls translated under -source $prev (gate missing)"
    elif grep -q "requires -source" "$outdir/stdout"; then
        neg_pass=$((neg_pass + 1))
        echo "  pass: java$ver $cls (-source $prev gates)"
    else
        neg_fail=$((neg_fail + 1))
        echo "  NEG FAIL: java$ver $cls (-source $prev) — error wasn't a version gate"
        sed -n 's/^/    /p' "$outdir/stdout" | head -3
    fi
}

for v in $versions; do
    dir="examples/java$v"
    [ -d "$dir" ] || continue
    echo "## java$v"
    for f in "$dir"/*.java; do
        [ -f "$f" ] || continue
        cls=$(basename "$f" .java)
        run_positive "$v" "$cls"
    done
    eval "neg_list=\$neg_$v"
    eval "prev=\$prev_for_$v"
    if [ -n "$neg_list" ] && [ -n "$prev" ]; then
        for cls in $neg_list; do
            [ -f "$dir/$cls.java" ] || continue
            run_negative "$v" "$cls" "$prev"
        done
    fi
done

echo
echo "Summary: positive $pass/$((pass+fail)), negative $neg_pass/$((neg_pass+neg_fail)), skipped $skip"
if [ $fail -gt 0 ] || [ $neg_fail -gt 0 ]; then
    exit 1
fi
exit 0
